//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsClient.MiServicioAritmetico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicioAritmetico.IServicioAritmetico")]
    public interface IServicioAritmetico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAritmetico/Sumar", ReplyAction="http://tempuri.org/IServicioAritmetico/SumarResponse")]
        ServicioAritmeticoDataContracts.Pareja Sumar(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAritmetico/Sumar", ReplyAction="http://tempuri.org/IServicioAritmetico/SumarResponse")]
        System.Threading.Tasks.Task<ServicioAritmeticoDataContracts.Pareja> SumarAsync(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAritmetico/Restar", ReplyAction="http://tempuri.org/IServicioAritmetico/RestarResponse")]
        ServicioAritmeticoDataContracts.Pareja Restar(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAritmetico/Restar", ReplyAction="http://tempuri.org/IServicioAritmetico/RestarResponse")]
        System.Threading.Tasks.Task<ServicioAritmeticoDataContracts.Pareja> RestarAsync(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAritmeticoChannel : WinFormsClient.MiServicioAritmetico.IServicioAritmetico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAritmeticoClient : System.ServiceModel.ClientBase<WinFormsClient.MiServicioAritmetico.IServicioAritmetico>, WinFormsClient.MiServicioAritmetico.IServicioAritmetico {
        
        public ServicioAritmeticoClient() {
        }
        
        public ServicioAritmeticoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAritmeticoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAritmeticoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAritmeticoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioAritmeticoDataContracts.Pareja Sumar(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b) {
            return base.Channel.Sumar(a, b);
        }
        
        public System.Threading.Tasks.Task<ServicioAritmeticoDataContracts.Pareja> SumarAsync(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b) {
            return base.Channel.SumarAsync(a, b);
        }
        
        public ServicioAritmeticoDataContracts.Pareja Restar(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b) {
            return base.Channel.Restar(a, b);
        }
        
        public System.Threading.Tasks.Task<ServicioAritmeticoDataContracts.Pareja> RestarAsync(ServicioAritmeticoDataContracts.Pareja a, ServicioAritmeticoDataContracts.Pareja b) {
            return base.Channel.RestarAsync(a, b);
        }
    }
}
